name: Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  make-lint:
    # Name the Job
    name: Runs linter
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:

      # installing dependencies
      - name: install dependencies
        run: make install

      # Runs the Linter action
      - name: Run Linter
        run: make lint